# Generated by Django 3.2 on 2022-09-12 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mobile',
            field=models.IntegerField(error_messages={'required': 'My custom error 1'}, unique=True),
        ),
    ]
