# Generated by Django 3.2 on 2022-09-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220912_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='account_type',
            field=models.CharField(choices=[('1', 'USER'), ('2', 'DELIVERYBOY')], max_length=50),
        ),
    ]
